version: '2'
services:
  nginx:
    image: evild/alpine-nginx:1.9.15-openssl
    container_name: lemp_nginx
    restart: always
    links:
      - php
    volumes:
      - ./html:/var/www/html/:ro
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - 80:80
      - 443:443
  php:
    image: phalconphp/php-fpm
    container_name: lemp_php
    restart: always
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db
    links:
      - db
    environment:
      - DB_NAME=lemp_bdd
      - TABLE_PREFIX=lemp_
      - DB_HOST=lemp
      - DB_PASSWORD=password
  db:
    image: mariadb:latest
    container_name: lemp_mariadb
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      
  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
  
  beanstalkd:
    image: schickling/beanstalkd
    command: beanstalkd -p 11300 -z 524288 -b /tmp
    ports:
      - 11300:11300
volumes:
  db-data:
    driver: local
